library(edgeR)
counts<-read.table("DilatedHF_FilteredCountdata.txt",check.names=FALSE)
colnames(counts)
group<-c(rep(1,5),rep(2,6))
design <- model.matrix(~group)
d=DGEList(counts=counts, group=group)
d=calcNormFactors(d)
plotMDS(d, labels=colnames(counts),col=c("blue","red")[factor(group)])
d=estimateDisp(d,design)
fit <- glmFit(d, design)
fit2 <- glmLRT(fit, coef = 2)
table.all <-topTags(fit2,n=Inf)
write.csv(table.all,file="TopTag_DCM_EdgeR.csv")
